DROP TABLE attendances CASCADE;

DROP TABLE lessons CASCADE;

DROP TABLE students CASCADE;

DROP TABLE schedules CASCADE;

DROP TABLE equipments CASCADE;

DROP TABLE groups CASCADE;

DROP TABLE rooms CASCADE;

DROP TABLE courses CASCADE;

DROP TABLE specialities CASCADE;

DROP TABLE specialities_courses CASCADE;
